#!/usr/bin/env bash

tail -n +2 "$1" > /tmp/post_contents
cpp -D__POST_TITLE="$(head -1 "$1" | cut -d\| -f1)" \
    -D__POST_FILE=\"/tmp/post_contents\" post.template.html | sed '/^#.*/d'
rm -f /tmp/post_contents
